name: Get latest measurements via knmi api
run-name: ${{ github.actor }} is testing get latest measurements.
on: workflow_dispatch
env:
  knmi_api_key: ${{ secrets.KNMI_API_KEY }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: cache virtualenv
      uses: actions/cache@v3
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-venv-
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Get data
      run: |
          python get_latest_measurements.py 
    - name: Commit and push CSV file
      run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add files/latest_measurements.csv
          git add streamlit_app.py
          git commit -m 'Add files/latest_measurements.csv csv'
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
