name: Make plots for daily predictions
run-name: ${{ github.actor }} is testing make plots for predictions
on: 
  schedule:
    - cron: '30 6 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Make plots for daily predictions
      run: python make_plots_for_predictions.py
    - name: Commit and push CSV file
      run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add images/preds_actuals_errors.png
          git add images/preds_actuals_confusion_matrix.png
          git commit -m 'Add plots for predictions to image folder'
          git push
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
